datasets:
  tvqa:
    build_info:
      annotations:
        test:
          storage: /home/hlpark/shared/REDUCE/REDUCE_benchmarks/SeViLA/sevila_data/tvqa/castle_s03e05_seg02_clip_22_val.json
          url: /home/hlpark/shared/REDUCE/REDUCE_benchmarks/SeViLA/sevila_data/tvqa/castle_s03e05_seg02_clip_22_val.json
        train:
          storage: /home/hlpark/shared/REDUCE/REDUCE_benchmarks/SeViLA/sevila_data/tvqa/castle_s03e05_seg02_clip_22_val.json
          url: /home/hlpark/shared/REDUCE/REDUCE_benchmarks/SeViLA/sevila_data/tvqa/castle_s03e05_seg02_clip_22_val.json
        val:
          storage: /home/hlpark/shared/REDUCE/REDUCE_benchmarks/SeViLA/sevila_data/tvqa/castle_s03e05_seg02_clip_22_val.json
          url: /home/hlpark/shared/REDUCE/REDUCE_benchmarks/SeViLA/sevila_data/tvqa/castle_s03e05_seg02_clip_22_val.json
      videos:
        storage: /home/hlpark/shared/TVQA/video/video_files
    data_type: videos
